[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
sbi-rt = { version = "0.0.2", features = ["legacy"] }

[[bin]]
name = "os"
path = "src/main.rs"
test = false
doctest = false
bench = false